### ISSUE TITLE
Faction save issue

### ISSUE THREAD

**Issue by RAINdevlopment** [Acenox/SaberFactions#2]
When anyone in my server creates a faction it works fine but after a restart server there faction is not there anymore. I am using version 2.6.2 on 1.16.4 with vault and essentialsX

**Comment by JorisPV** [comment]
Hello, 

Hello, I am not developing SaberFaction, if you have any problem please contact SaberFaction Official Support here: https://discord.com/invite/x9gGZ4E

Best regards,
